version: '3.9'

services:
  nginx:
    container_name: nginx
    image: nginx:1.13
    ports:
      - 80:80
      - 443:443
    volumes:
      - ./nginx/conf.d:/etc/nginx/conf.d

  angular:
    container_name: angular
    build: ./angularClient
    ports:
      - 4200:4200

  java_db:
    container_name: mysql
    image: mysql
    environment:
      MYSQL_ROOT_PASSWORD: $MYSQL_ROOT_PASSWORD
      MYSQL_DATABASE: $MYSQL_DATABASE
      MYSQL_PASSWORD: $MYSQL_PASSWORD
    ports:
      - 3306:3306

  springboot:
    container_name: springboot
    build: ./angularClient_backend
    ports:
      - 8080:8080
    environment:
      - DATABASE_URL=$DATABASE_URL
      - DATABASE_USERNAME=$DATABASE_USERNAME
      - DATABASE_PASSWORD=$DATABASE_PASSWORD
    depends_on:
      - java_db
