version: '3.9'

services:
  nginx:
    container_name: nginx
    image: nginx:1.13
    ports:
      - 80:80
      - 443:443
    volumes:
      - ./nginx/conf.d:/etc/nginx/conf.d

  angular:
    container_name: angular
    build: ./angularClient
    ports:
      - 4200:4200

  java_db:
    container_name: mysql
    image: mysql
    environment:
      MYSQL_ROOT_PASSWORD: PeneFlaciszon76
      MYSQL_DATABASE: name
      MYSQL_PASSWORD: PeneFlaciszon76
    ports:
      - 3306:3306

  springboot:
    container_name: springboot
    build: ./angularClient_backend
    ports:
      - 8080:8080
    environment:
      - DATABASE_URL=jdbc:mysql://java_db:3306/name?serverTimezone=UTC
      - DATABASE_USERNAME=root
      - DATABASE_PASSWORD=PeneFlaciszon76
    depends_on:
      - java_db
